export const INIT_ANIMES = 'INIT_ANIMES';
export const INIT_ANIMES_SUCCESS = 'INIT_ANIMES_SUCCESS';
export const INIT_ANIMES_FAIL = 'INIT_ANIMES_FAIL';

export const INIT_LINKS = 'INIT_LINKS';

export const FETCH_NEXT_ANIME_PAGE = 'FETCH_NEXT_ANIME_PAGE';
export const FETCH_NEXT_ANIME_PAGE_SUCCESS = 'FETCH_NEXT_ANIME_PAGE_SUCCESS';
export const FETCH_NEXT_ANIME_PAGE_FAIL = 'FETCH_NEXT_ANIME_PAGE_FAIL';

export const FETCH_PREVIOUS_ANIME_PAGE = 'FETCH_PREVIOUS_ANIME_PAGE';
export const FETCH_PREVIOUS_ANIME_PAGE_SUCCESS =
  'FETCH_PREVIOUS_ANIME_PAGE_SUCCESS';
export const FETCH_PREVIOUS_ANIME_PAGE_FAIL = 'FETCH_PREVIOUS_ANIME_PAGE_FAIL';

export const SEARCH_ANIME = 'SEARCH_ANIME';
export const SEARCH_ANIME_SUCCESS = 'SEARCH_ANIME_SUCCESS';
export const SEARCH_ANIME_FAIL = 'SEARCH_ANIME_FAIL';

export const INIT_SINGLE_ANIME = 'INIT_SINGLE_ANIME';
export const INIT_SINGLE_ANIME_SUCCESS = 'INIT_SINGLE_ANIME_SUCCESS';
export const INIT_SINGLE_ANIME_FAIL = 'INIT_SINGLE_ANIME_FAIL';
