export {
  initAnimes,
  initAnimesSuccess,
  initAnimesFail,
  initLinks,
  fetchNextAnimePage,
  fetchNextAnimePageSuccess,
  fetchNextAnimePageFail,
  fetchPreviousAnimePage,
  fetchPreviousAnimePageSuccess,
  fetchPreviousAnimePageFail,
  searchAnime,
  searchAnimeSucces,
  searchAnimeFail,
  initSingleAnime,
  initSingleAnimeSuccess,
  initSingleAnimeFail,
} from './animes';
